spring:
  application:
    name: chat-application
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8100
#  servlet:
#    context-path: /chat-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/