spring:
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 8080

eureka:
  instance:
    metadataMap:
      prometheus:
        path: /actuator/prometheus

ribbon:
  retryableStatusCodes: 503, 504
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ConnectTimeout: 1500
  ReadTimeout: 7500
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 18000

authentication:
  user:
    max-inactivity-time-in-minutes: 15
  token:
    key: '{cipher}AQB3jq7nyRssSgpDSTcDgNtHZIOtdO2wQzIO6Ghxw6LxMmMZgLNKbXSQIiKFKg7O8qWZ5Id0H8PqGCt5Qu7dpdfezqW36J0KhkhcwUQz9+pfYHgFhTDZYoMv2oYsNYIeodu4YxEvll12qWnpk5F7lV9tuHWrAuy5eX8CZZUst3f6Op4NmhjzhUirFauQ5fwv8kwHMtt3V4JCB+tw4t0pNG7Ks4HQMTGzKo18vXxzKCmKACXaePUYZKU1BNVxPQO0QU574U4L0zMD6+I9XFHBjqLif9VsBAzIAoVguJm7rfnvHE0SVaXV7960xIqqgh6pMhA5ZabMfJTeCKrynSAAV1Xdqk9V3AiEo29a9CoP96PHKzX484Rx3rsksk0PLR8KhRA='


---
spring:
  profiles: test-hosts

server:
  port: 8080

authentication:
  user:
    max-inactivity-time-in-minutes: 15
  token:
    key: '{cipher}AQB3jq7nyRssSgpDSTcDgNtHZIOtdO2wQzIO6Ghxw6LxMmMZgLNKbXSQIiKFKg7O8qWZ5Id0H8PqGCt5Qu7dpdfezqW36J0KhkhcwUQz9+pfYHgFhTDZYoMv2oYsNYIeodu4YxEvll12qWnpk5F7lV9tuHWrAuy5eX8CZZUst3f6Op4NmhjzhUirFauQ5fwv8kwHMtt3V4JCB+tw4t0pNG7Ks4HQMTGzKo18vXxzKCmKACXaePUYZKU1BNVxPQO0QU574U4L0zMD6+I9XFHBjqLif9VsBAzIAoVguJm7rfnvHE0SVaXV7960xIqqgh6pMhA5ZabMfJTeCKrynSAAV1Xdqk9V3AiEo29a9CoP96PHKzX484Rx3rsksk0PLR8KhRA='
