spring:
  application:
    name: web-api-gateway

server:
  port: ${SERVER_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

authentication:
  token:
    key: ${AUTHENTICATION_TOKEN_KEY:test}

ribbon:
  ConnectTimeout: 1500
  ReadTimeout: 7500
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

---
spring:
  profiles: test-hosts

server:
  port: 8080