spring:
  application:
    name: theory-application-service

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/theory
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 0
  servlet:
    context-path: /chemistry-lessons/