spring:
  application:
    name: theory-application

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/theory
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver