server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: test-localhost
server:
  port: 8761

---
spring:
  profiles: test-hosts
server:
  port: 8761
