spring:
  application:
    name: service-discovery
server:
  port: ${SERVER_PORT}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

---
spring:
  profiles: test-localhost
server:
  port: ${SERVER_PORT:8761}

---
spring:
  profiles: test-hosts
server:
  port: ${SERVER_PORT:8761}
