spring:
  application:
    name: config-service

server:
  port: ${SERVER_PORT}

---
spring:
  profiles: test-host, native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: ${SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS:file:////opt/config-repo}
#        git:
#          uri: file:///${CONFIG-REPO-ENV}
#          clone-on-start: true
#          force-pull: true

  security:
    user:
      name: ${SRPING_CLOUD_USER_NAME:config-user-name}
      password: ${CONFIG_SERVICE_PASSWORD:123}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}


server:
  port: ${SERVER_PORT:8888}