version: '3'


services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ../theory-service/psql/scripts/theory_application.sql:/docker-entrypoint-initdb.d/init_theory_appication.sql
    environment:
      POSTGRES_PASSWORD: postgres

  manager:
    image: 'sheepkiller/kafka-manager'
    ports:
      - '9000:9000'
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
