spring:
  application:
    name: community-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/comment_db
    username: root
    password: mameluko
    platform: postgres
    driver-class-name: org.postgresql.Driver

#server:
#  port: 0
#  servlet:
#    context-path: /theory-application/
#
#kafka:
#  server: http://localhost:9092
#  groupId: chemistry-theory.1
