spring:
  application:
    name: community-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:postgresql://localhost:5432/comment_db
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8082

kafka:
  server: localhost:9092
  groupId: group_json1
