spring:
  application:
    name: authorization-application
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/users_autentication
    username: mick
    password: mick
    platform: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db.migration

server:
  port: 0
  servlet:
    context-path: /authorization-application/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  server: http://localhost:9092
  groupId: authorization-user-event.2


user:
  jwt:
    secretKey: chemcool
    header: Authorization
    validityTokenInMilliSeconds: 20000
    validityRefreshTokenInMilliSeconds: 3600000